log_level: 10 # 0: notset, 10:debug, 20:info, 30:warning, 40: error, 50:critical
log_file_number_limit: 5 # Number of log file (per file with max size is log_file_size_limit)
log_file_size_limit: 200 # MBytes
log_keep_days: 14
log_cleaning_time: 60  # Minutes

server_relay:
  host: '192.168.1.98'
  port: 42222

rabbit_server:
  server: '127.0.0.1'
  port: 5672
  user: 'telequoteFeed'
  password: 'Chunming0684'

amqp_publisher_info:
  exchange: 'amq.topic'
  exchange_type: 'topic'  # 'direct', 'fanout', 'headers', 'topic'
  duable: True
  routing_key: 'example.changed'

amqp_latest_data_info:
  interval: 0.5
  routing_key: 'example.initial'

publisher_option:
  time: 0.01 # seconds

# ['EUR A0-FX', 'GBP A0-FX', 'XAU A0-FX', 'SN1Z2', 'SN1C1', 'AUD A0-FX', 'CHF A0-FX', 'JPY A0-FX', 'GHSIZ2', 'GHSIH3', 'GHSIX2', 'GHSIC1']
counter_filter: ['A0-FX']
